project_id   = "your-gcp-project-id"
region       = "us-central1"
network      = "default"
app_image    = "gcr.io/your-gcp-project-id/your-app-image"
db_password  = "your-db-password"
db_user      = "root"
